MODEL:
  DEVICE: 'cuda'
  DEVICE_ID: ('0')
  PRETRAIN_CHOICE: 'self'
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  FREEZE: 0.9


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10

DATASETS:
  NAMES: ('kpneuma')
  ROOT_DIR: 'data/'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 40
  BASE_LR: 0.00035

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40 # 1
  LOG_PERIOD: 20
  EVAL_PERIOD: 40 # 1

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "saved_models/visual/KPNEUMA/resnet50_model_40.pth"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "saved_models/visual/KPNEUMA/"

